config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, skip: :all

  if ENV["REDIRECT_TO_DIGITAL_IDENTITY"] == "true"
    get "/", to: redirect("https://www.gov.uk/account/home")

    get "/feedback", to: redirect("https://signin.account.gov.uk/support")

    get "/sign-in", to: redirect("https://www.gov.uk/sign-in/redirect")
    get "/sign-in/*path", to: redirect("https://www.gov.uk/sign-in/redirect")

    get "/account/", to: redirect("https://www.gov.uk/account/home")
    get "/account/*path", to: redirect("https://www.gov.uk/account/home")

    get "/new-account", to: redirect("https://www.gov.uk/sign-in/redirect")
    get "/new-account/*path", to: redirect("https://www.gov.uk/sign-in/redirect")

    get "/healthcheck", to: "healthcheck#show"
    get "*path", to: proc { [404, {}, ["not found"]] }
  else
    devise_scope :user do
      get "/", to: "welcome#show", as: :welcome

      get "/feedback", to: "feedback#show", as: :feedback_form
      post "/feedback", to: "feedback#submit", as: :feedback_form_submitted

      scope "/sign-in" do
        get  "/", to: "sessions#create", as: :new_user_session
        post "/", to: "sessions#create"
        get  "/phone/code", to: "sessions#phone_code", as: :user_session_phone_code
        post "/phone/verify", to: "sessions#phone_verify", as: :user_session_phone_verify
        get  "/phone/resend", to: "sessions#phone_resend", as: :user_session_phone_resend
        post "/phone/resend", to: "sessions#phone_resend_code"
      end

      get "/sign-out", to: "sessions#destroy", as: :destroy_user_session

      get "/login", to: redirect(path: "/sign-in")
      get "/logout", to: redirect(path: "/sign-out")

      scope "/account" do
        get "/insecure-password", to: "insecure_password#show", as: :insecure_password_interstitial

        get "/manage", to: "manage#show", as: :account_manage
        get "/security", to: "security#show", as: :account_security
        get "/security/activity/:page_number", to: "security#paginated_activity", as: :account_security_paginated_activity
        get "/security/code/:page_number", to: "security#paginated_mfa_tokens", as: :account_security_paginated_mfa_tokens

        get    "/delete", to: "delete#show", as: :account_delete
        get    "/delete/confirmation", to: "delete#confirmation", as: :account_delete_confirmation

        get   "/", to: "account#show"

        scope "/mfa" do
          get "/abort", to: "redo_mfa#stop", as: :redo_mfa_stop

          scope "/phone" do
            get  "/code", to: "redo_mfa_phone#code", as: :redo_mfa_phone_code
            post "/verify", to: "redo_mfa_phone#verify", as: :redo_mfa_phone_verify
            get  "/resend", to: "redo_mfa_phone#resend", as: :redo_mfa_phone_resend
            post "/resend", to: "redo_mfa_phone#resend_code"
          end
        end

        scope "/edit" do
          get  "/email", to: "registrations#edit_email", as: :edit_user_registration_email
          get  "/password", to: "registrations#edit_password", as: :edit_user_registration_password

          scope "/phone" do
            get  "/", to: "edit_phone#show", as: :edit_user_registration_phone
            get "/new", to: "edit_phone#new", as: :edit_user_registration_phone_new
            get  "/code", to: "edit_phone#code", as: :edit_user_registration_phone_code
            get  "/resend", to: "edit_phone#resend", as: :edit_user_registration_phone_resend
          end

          scope "/consent" do
            get  "/cookie", to: "edit_consent#cookie", as: :edit_user_consent_cookie
            get  "/feedback", to: "edit_consent#feedback", as: :edit_user_consent_feedback
          end
        end

        scope "/password" do
          get "/new", to: "passwords#new", as: :new_user_password
          get "/edit", to: "passwords#edit", as: :edit_user_password

          scope "/reset" do
            get "/", to: "passwords#new", as: :reset_password
            get "/sent", to: "passwords#sent", as: :reset_password_sent
          end
        end

        scope "/confirmation" do
          get  "/", to: "confirmations#show", as: :user_confirmation
          post "/", to: "confirmations#create"

          get "/new", to: "confirmations#new", as: :new_user_confirmation
          get "/sent", to: "confirmations#sent", as: :confirmation_email_sent
        end

        scope "/unlock" do
          get  "/", to: "unlocks#show", as: :user_unlock
          post "/", to: "unlocks#create"
          get  "/new", to: "unlocks#new", as: :new_user_unlock
        end
      end

      scope "/new-account" do
        get  "/", to: "registrations#start", as: :new_user_registration_start
        post "/", to: "registrations#redirect_to_create_account"
        get  "/phone/code", to: "registrations#redirect_to_create_account"
        post "/phone/verify", to: "registrations#redirect_to_create_account"
        get  "/phone/resend", to: "registrations#redirect_to_create_account"
        post "/phone/resend", to: "registrations#redirect_to_create_account"
        get  "/your-information", to: "registrations#redirect_to_create_account"
        post "/your-information", to: "registrations#redirect_to_create_account"
        get  "/finish", to: "registrations#redirect_to_create_account"
        get  "/cancel", to: "registrations#redirect_to_create_account"

        get "/welcome", to: redirect(path: "/sign-in")
      end
    end

    namespace :api do
      namespace :v1 do
        get "/deanonymise-token", to: "deanonymise_token#show"
        get "/ephemeral-state", to: "ephemeral_state#show"

        namespace :report do
          get "/general", to: "general#show"

          post "/bigquery", to: "bigquery#create"
        end
      end
    end

    post "/redirect-to-previous-url", to: "redirect_to_previous_url#show", as: :redirect_to_previous_url

    use_doorkeeper
    use_doorkeeper_openid_connect

    get "/healthcheck", to: "healthcheck#show"
  end

  get "/404", to: "standard_errors#not_found"
  get "/429", to: "standard_errors#too_many_requests"
  get "/422", to: "standard_errors#unprocessable_entity"
  get "/500", to: "standard_errors#internal_server_error"

  mount GovukPublishingComponents::Engine, at: "/component-guide" if Rails.env.development?

  get "/account/home", to: proc { [200, {}, ["fake account dashboard page for feature tests"]] } if Rails.env.test?
end

app/controllers/edit_phone_controller.rb
class EditPhoneController < ApplicationController
  include ChangeCoreCredentials

  before_action :authenticate_user!
  before_action :enforce_recent_mfa!

  helper_method :resource
  helper_method :setting_up_first_phone?
  helper_method :start_path

  def new
    redirect_to edit_user_registration_phone_path unless setting_up_first_phone?

    @resource_error_messages = {}
  end

  def show
    redirect_to edit_user_registration_phone_new_path if setting_up_first_phone?

    @resource_error_messages = {}
  end

  def confirm
    @resource_error_messages = {}

    unless current_user.valid_password? params[:current_password]
      @resource_error_messages[:current_password] = [
        I18n.t("activerecord.errors.models.user.attributes.password.#{params[:current_password].blank? ? 'blank' : 'invalid'}"),
      ]
    end

    if params[:phone]
      phone_number = MultiFactorAuth.e164_number(params[:phone])

      if phone_number == current_user.phone
        @resource_error_messages[:phone] = [
          I18n.t("mfa.errors.phone.nochange"),
        ]
      end

      unless MultiFactorAuth.valid? phone_number
        @resource_error_messages[:phone] = [
          I18n.t("activerecord.errors.models.user.attributes.phone.invalid"),
        ]
      end
    else
      @resource_error_messages[:phone] = [
        I18n.t("activerecord.errors.models.user.attributes.phone.blank"),
      ]
    end

    if @resource_error_messages.any?
      render setting_up_first_phone? ? :new : :show
    else
      current_user.update!(unconfirmed_phone: phone_number)
    end
  end

  def code
    @resource_error_messages = {}
  end

  def code_send
    redirect_to start_path and return unless current_user.unconfirmed_phone

    MultiFactorAuth.generate_and_send_code(current_user, use_unconfirmed: true)

    @resource_error_messages = {}
    render :code
  end

  def verify
    state = MultiFactorAuth.verify_code(current_user, params[:phone_code])
    if state == :ok
      old_phone = current_user.phone || "nothing"
      new_phone = current_user.unconfirmed_phone
      current_user.update!(
        phone: new_phone,
        unconfirmed_phone: nil,
        last_mfa_success: Time.zone.now,
      )
      record_security_event(SecurityActivity::PHONE_CHANGED, user: current_user, notes: "from #{old_phone} to #{new_phone}")
      UserMailer.with(user: current_user).change_phone_email.deliver_later
      session[:level_of_authentication] = :level1
      session[:has_done_mfa] = true
      redirect_to session.delete(:after_change_phone_path) || account_manage_path
    else
      @resource_error_messages = {
        phone_code: [
          I18n.t("mfa.errors.phone_code.#{state}", resend_link: edit_user_registration_phone_resend_path),
        ],
      }
      render :code
    end
  end

  def resend
    redirect_to start_path unless current_user.unconfirmed_phone
  end

private

  def resource; end

  def start_path
    if setting_up_first_phone?
      edit_user_registration_phone_new_path
    else
      edit_user_registration_phone_path
    end
  end

  def setting_up_first_phone?
    current_user.phone.nil?
  end

  def enforce_recent_mfa!
    redo_mfa edit_user_registration_phone_path if must_redo_mfa?
  end
end

app/views/edit_phone/code.html.erb
<% content_for :title, t("mfa.phone.code.page_title") %>
<%= render "govuk_publishing_components/components/heading", {
  text: yield(:title),
  heading_level: 1,
  margin_bottom: 3,
} %>

<% t("mfa.phone.code.description").each do |msg| %>
  <p class="govuk-body"><%= sanitize(msg) %></p>
<% end %>

<%= form_with(url: edit_user_registration_phone_verify_path, method: :post, html: { autocomplete: "off" }) do %>
  <% if @resource_error_messages.any? %>
    <%= render "_shared/error_messages", resource: nil, resource_error_messages: @resource_error_messages %>
  <% end %>

  <%= render "govuk_publishing_components/components/input", {
    label: { text: t("mfa.phone.code.fields.phone_code.label") },
    name: "phone_code",
    maxlength: 6,
    type: "number",
    error_message: devise_error_items(:phone_code, @resource_error_messages),
    width: 5,
  } %>

  <%= render "govuk_publishing_components/components/button", {
    text: t("mfa.phone.code.fields.submit.label"),
    margin_bottom: true
  } %>
<% end %>

<%= render "govuk_publishing_components/components/heading", {
  text: t("mfa.phone.code.not_received.change_heading"),
  heading_level: 2,
  margin_bottom: 4,
  font_size: "m",
} %>

<p class="govuk-body">
  <%= sanitize(t("mfa.phone.code.not_received.resend_message", link: edit_user_registration_phone_resend_path)) %>
</p>

app/views/edit_phone/confirm.html.erb
<% content_for :title, t("mfa.phone.update.confirm.heading") %>
<% unless setting_up_first_phone? %>
  <% content_for :location, "manage" %>
  <% content_for :account_navigation do %>
    <%= render "account-navigation", page_is: yield(:location) %>
  <% end %>
<% end %>

<% content_for :before_main do %>
  <%= render "govuk_publishing_components/components/back_link", { href: start_path } %>
<% end %>

<%= render "govuk_publishing_components/components/heading", {
  text: yield(:title),
  heading_level: 1,
  font_size: "l",
  margin_bottom: 6,
} %>

<% t("mfa.phone.update.confirm.description", phone_number: MultiFactorAuth.formatted_phone_number(current_user.unconfirmed_phone)).each do |msg| %>
  <p class="govuk-body"><%= sanitize(msg) %></p>
<% end %>

<%= form_with(url: edit_user_registration_phone_code_path, method: :post) do %>
  <%= render "govuk_publishing_components/components/button", {
    text: t("mfa.phone.update.confirm.fields.submit.label"),
    margin_bottom: true
  } %>
<% end %>

<p class="govuk-body">
  <%= sanitize(t("mfa.phone.code.not_received.change_number_message", link: edit_user_registration_phone_resend_path)) %>
</p>

app/views/edit_phone/new.html.erb
<% content_for :title, t("mfa.phone.update.start.new.heading") %>

<%= render "govuk_publishing_components/components/heading", {
  text: yield(:title),
  heading_level: 1,
  font_size: "l",
  margin_bottom: 6,
} %>

<% t("mfa.phone.update.start.new.description").each do |msg| %>
  <p class="govuk-body"><%= sanitize(msg) %></p>
<% end %>

<%= form_with(url: edit_user_registration_phone_confirm_path, method: :post, data: { module: "gem-track-click" }) do %>
  <% if @resource_error_messages.any? %>
    <%= render "_shared/error_messages", resource: nil, resource_error_messages: @resource_error_messages %>
  <% end %>

  <%= render "govuk_publishing_components/components/input", {
    label: { text: t("mfa.phone.update.start.new.fields.phone.label") },
    name: "phone",
    type: "tel",
    error_message: devise_error_items(:phone, @resource_error_messages),
  } %>

  <p class="govuk-body">
    <%= t("mfa.phone.update.start.new.message") %>
  </p>

  <%= render "govuk_publishing_components/components/show_password", {
    label: {
      text: t("devise.registrations.edit.fields.current_password.label"),
    },
    heading_size: "m",
    hint: t("devise.registrations.edit.fields.current_password.hint"),
    name: "current_password",
    error_message: devise_error_items(:current_password, @resource_error_messages),
    autocomplete: "current-password",
    data: {
      button_track_action: "passwordShowHide",
      button_track_category: "pageElementInteraction",
      button_track_label: "changePhoneNumber"
    }
  } %>

  <%= render "govuk_publishing_components/components/button", {
    text: t("mfa.phone.update.start.new.fields.submit.label"),
  } %>
<% end %>

app/views/edit_phone/resend.html.erb
<% content_for :title, t("mfa.phone.resend.heading") %>

<% content_for :before_main do %>
  <%= render "govuk_publishing_components/components/back_link", { href: edit_user_registration_phone_code_path } %>
<% end %>

<%= render "govuk_publishing_components/components/heading", {
  text: yield(:title),
  heading_level: 1,
  font_size: "xl",
  margin_bottom: 3,
} %>

<p class="govuk-body"><%= t("mfa.phone.resend.description") %></p>

<%= form_with(url: edit_user_registration_phone_code_path, method: :post) do %>
  <%= render "govuk_publishing_components/components/button", {
    text: t("mfa.phone.resend.fields.submit.label"),
  } %>
<% end %>

app/views/edit_phone/show.html.erb
<% content_for :title, t("mfa.phone.update.start.show.heading") %>
<% content_for :location, "manage" %>
<% content_for :account_navigation do %>
  <%= render "account-navigation", page_is: yield(:location) %>
<% end %>

<% content_for :before_main do %>
  <%= render "govuk_publishing_components/components/back_link", { href: account_manage_path } %>
<% end %>

<%= render "migration-edit-warning" %>